# Generated by Django 3.2.9 on 2021-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_roomclass_numberofpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservicetype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True),
        ),
        migrations.AddField(
            model_name='foodtype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True),
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True),
        ),
    ]
