# Generated by Django 3.2.9 on 2021-11-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomclass_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='comment',
            field=models.CharField(blank=True, db_column='Comment', max_length=200, null=True),
        ),
    ]
