# Generated by Django 3.2.9 on 2021-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foodtype_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='citizenship',
            field=models.CharField(blank=True, db_column='Citizenship', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='passport',
            field=models.CharField(blank=True, db_column='Passport', max_length=15, null=True),
        ),
    ]
