# Generated by Django 3.2.9 on 2021-11-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211128_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotelnumber',
        ),
    ]
