# Generated by Django 3.2.9 on 2021-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_room_hotelnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phonenumber',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=19, null=True),
        ),
    ]
