# Generated by Django 3.2.9 on 2021-12-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_visitor_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='addservices',
            options={'managed': True, 'verbose_name': 'Доп. услуга', 'verbose_name_plural': 'Доп. услуги'},
        ),
        migrations.AlterModelOptions(
            name='addservicetype',
            options={'managed': True, 'verbose_name': 'Тип доп. услуги', 'verbose_name_plural': 'Типы доп. услуг'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'managed': True, 'verbose_name': 'Питание', 'verbose_name_plural': 'Питание'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'managed': True, 'verbose_name': 'Тип питания', 'verbose_name_plural': 'Типы питания'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'managed': True, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'managed': True, 'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'managed': True, 'verbose_name': 'Тип оплаты', 'verbose_name_plural': 'Типы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True, 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='roomclass',
            options={'managed': True, 'verbose_name': 'Класс номера', 'verbose_name_plural': 'Классы номеров'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'managed': True, 'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.AlterField(
            model_name='addservices',
            name='addservicesid',
            field=models.AutoField(db_column='AddServicesId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='addservices',
            name='addservicetypeid',
            field=models.ForeignKey(blank=True, db_column='AddServiceTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.addservicetype', verbose_name='Тип доп. услуги'),
        ),
        migrations.AlterField(
            model_name='addservices',
            name='orderid',
            field=models.ForeignKey(blank=True, db_column='OrderId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.orderinfo', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='addservicetype',
            name='addservicetypeid',
            field=models.AutoField(db_column='AddServiceTypeId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='addservicetype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='addservicetype',
            name='cost',
            field=models.PositiveIntegerField(blank=True, db_column='Cost', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='addservicetype',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodid',
            field=models.AutoField(db_column='FoodId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodtypeid',
            field=models.ForeignKey(blank=True, db_column='FoodTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.foodtype', verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='food',
            name='orderid',
            field=models.ForeignKey(blank=True, db_column='OrderId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.orderinfo', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='comment',
            field=models.CharField(blank=True, db_column='Comment', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='cost',
            field=models.PositiveIntegerField(blank=True, db_column='Cost', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='foodtypeid',
            field=models.AutoField(db_column='FoodTypeId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='checkindate',
            field=models.DateField(blank=True, db_column='CheckInDate', null=True, verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='checkoutdate',
            field=models.DateField(blank=True, db_column='CheckOutDate', null=True, verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='cost',
            field=models.IntegerField(blank=True, db_column='Cost', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='numberofguests',
            field=models.IntegerField(blank=True, db_column='NumberOfGuests', null=True, verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='orderid',
            field=models.AutoField(db_column='OrderId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='roomid',
            field=models.ForeignKey(blank=True, db_column='RoomId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='visitorid',
            field=models.ForeignKey(blank=True, db_column='VisitorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.visitor', verbose_name='Посетитель'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderactive',
            field=models.IntegerField(blank=True, db_column='OrderActive', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderid',
            field=models.ForeignKey(blank=True, db_column='OrderId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.orderinfo', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderpayed',
            field=models.IntegerField(blank=True, db_column='OrderPayed', null=True, verbose_name='Оплаченный'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderstatusid',
            field=models.AutoField(db_column='OrderStatusId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='paymenttypeid',
            field=models.ForeignKey(blank=True, db_column='PaymentTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.paymenttype', verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=30, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='paymenttypeid',
            field=models.AutoField(db_column='PaymentTypeId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='room',
            name='avaliable',
            field=models.IntegerField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomclassid',
            field=models.ForeignKey(blank=True, db_column='RoomClassId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.roomclass', verbose_name='Класс номера'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomid',
            field=models.AutoField(db_column='RoomId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomnumber',
            field=models.PositiveIntegerField(blank=True, db_column='RoomNumber', null=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='comment',
            field=models.CharField(blank=True, db_column='Comment', max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='cost',
            field=models.PositiveIntegerField(blank=True, db_column='Cost', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=30, null=True, verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='numberofpeople',
            field=models.PositiveIntegerField(blank=True, db_column='NumberOfPeople', null=True, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='roomclass',
            name='roomclassid',
            field=models.AutoField(db_column='RoomClassId', primary_key=True, serialize=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='citizenship',
            field=models.CharField(blank=True, db_column='Citizenship', max_length=30, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='firstname',
            field=models.CharField(blank=True, db_column='Firstname', max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='lastname',
            field=models.CharField(blank=True, db_column='Lastname', max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='login',
            field=models.CharField(blank=True, db_column='Login', max_length=30, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='passport',
            field=models.CharField(blank=True, db_column='Passport', max_length=15, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='passwordhash',
            field=models.CharField(blank=True, db_column='PasswordHash', max_length=64, null=True, verbose_name='Хеш пароля'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='patronymic',
            field=models.CharField(blank=True, db_column='Patronymic', max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phonenumber',
            field=models.CharField(blank=True, db_column='PhoneNumber', max_length=19, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='session',
            field=models.CharField(blank=True, db_column='Session', max_length=32, null=True, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorid',
            field=models.AutoField(db_column='VisitorId', primary_key=True, serialize=False, verbose_name='№'),
        ),
    ]
