# Generated by Django 3.2.9 on 2021-12-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211209_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addservicetype',
            options={'managed': True, 'verbose_name': 'Набор доп. услуг', 'verbose_name_plural': 'Наборы доп. услуг'},
        ),
        migrations.AlterField(
            model_name='visitor',
            name='session',
            field=models.CharField(blank=True, db_column='Session', max_length=32, null=True, verbose_name='Сессионный ключ'),
        ),
    ]
