# Generated by Django 3.2.9 on 2021-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211211_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='cost',
            field=models.PositiveIntegerField(blank=True, db_column='Cost', null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='numberofguests',
            field=models.PositiveIntegerField(blank=True, db_column='NumberOfGuests', null=True, verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='room',
            name='avaliable',
            field=models.BooleanField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
    ]
