# Generated by Django 3.2.9 on 2021-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211211_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addservicetype',
            name='avaliable',
            field=models.BooleanField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='avaliable',
            field=models.BooleanField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderactive',
            field=models.BooleanField(blank=True, db_column='OrderActive', null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='orderpayed',
            field=models.BooleanField(blank=True, db_column='OrderPayed', null=True, verbose_name='Оплаченный'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='avaliable',
            field=models.BooleanField(blank=True, db_column='Avaliable', null=True, verbose_name='Активный'),
        ),
    ]
