# Generated by Django 3.2.9 on 2021-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_visitor_visitorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='included',
            field=models.BooleanField(blank=True, db_column='Included', null=True, verbose_name='Включено в заказ'),
        ),
    ]
